// GENERADO por generate.py. No editar a mano.
// Sale de la MISMA fuente que schema.sql, así que columnas y mapeo no se desalinean.

export type FieldKind = 'text'|'number'|'boolean'|'date'|'datetime'|'json'|'array'|'link'|'linkMany';

export interface FieldDef { col: string; kind: FieldKind; target?: string; join?: string; selfCol?: string; otherCol?: string }
export interface ConflictTarget { cols: string[]; where?: string }
export interface TableDef { table: string; fields: Record<string, FieldDef>; conflictTarget?: ConflictTarget }

export const SCHEMA: Record<string, TableDef> = {
  Users: {
    table: 'users',
    fields: {
      id: { col: 'id', kind: 'text' },
      email: { col: 'email', kind: 'text' },
      firstName: { col: 'first_name', kind: 'text' },
      lastName: { col: 'last_name', kind: 'text' },
      role: { col: 'role', kind: 'text' },
      lastActiveAt: { col: 'last_active_at', kind: 'datetime' },
      purchaseLevel: { col: 'purchase_level', kind: 'text' },
      costCenters: { col: 'cost_centers', kind: 'array' },
      accessComercial: { col: 'access_comercial', kind: 'text' },
      accessOperacion: { col: 'access_operacion', kind: 'text' },
      accessAdmin: { col: 'access_admin', kind: 'text' },
      accessFinanzas: { col: 'access_finanzas', kind: 'text' },
      accessOtros: { col: 'access_otros', kind: 'text' },
      maxApprovalAmount: { col: 'max_approval_amount', kind: 'number' },
      visiblePages: { col: 'visible_pages', kind: 'array' },
      hiddenFromChat: { col: 'hidden_from_chat', kind: 'boolean' },
      profilePhoto: { col: 'profile_photo', kind: 'text' },
      departamento: { col: 'departamento', kind: 'text' },
      dashboardWidgets: { col: 'dashboard_widgets', kind: 'array' },
      widgetLayout: { col: 'widget_layout', kind: 'text' },
      activeChannel: { col: 'active_channel', kind: 'text' },
      cotizacionRubros: { col: 'cotizacion_rubros', kind: 'array' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Projects: {
    table: 'projects',
    fields: {
      id: { col: 'id', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      fullName: { col: 'full_name', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      client: { col: 'client', kind: 'text' },
      budget: { col: 'budget', kind: 'number' },
      startDate: { col: 'start_date', kind: 'date' },
      endDate: { col: 'end_date', kind: 'date' },
      description: { col: 'description', kind: 'text' },
      tematica: { col: 'tematica', kind: 'text' },
      timelineStatus: { col: 'timeline_status', kind: 'text' },
      timelineUrl: { col: 'timeline_url', kind: 'text' },
      timelineUpdatedAt: { col: 'timeline_updated_at', kind: 'datetime' },
      teamsChannelUrl: { col: 'teams_channel_url', kind: 'text' },
      teamsChannelStatus: { col: 'teams_channel_status', kind: 'text' },
      dealVinculado: { col: 'deal_vinculado_id', kind: 'link', target: 'deals' },
      lider: { col: 'lider_id', kind: 'link', target: 'users' },
      muestra: { col: 'muestra', kind: 'text' },
      muestraImagen: { col: 'muestra_imagen', kind: 'text' },
      instruccionesDeAnalisis: { col: 'instrucciones_de_analisis', kind: 'text' },
      lastAnalysisJson: { col: 'last_analysis_json', kind: 'text' },
      lastAnalysisAt: { col: 'last_analysis_at', kind: 'datetime' },
      createdBy: { col: 'created_by', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' },
      analistas: { col: 'analistas', kind: 'linkMany', join: 'projects_analistas', selfCol: 'project_id', otherCol: 'user_id' },
      moderadores: { col: 'moderadores', kind: 'linkMany', join: 'projects_moderadores', selfCol: 'project_id', otherCol: 'user_id' },
      asistentes: { col: 'asistentes', kind: 'linkMany', join: 'projects_asistentes', selfCol: 'project_id', otherCol: 'user_id' }
    },
  },
  CRMItems: {
    table: 'crm_items',
    fields: {
      id: { col: 'id', kind: 'text' },
      itemName: { col: 'item_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      client: { col: 'client', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      proposalDate: { col: 'proposal_date', kind: 'date' },
      contractDate: { col: 'contract_date', kind: 'date' },
      budget: { col: 'budget', kind: 'number' },
      revenue: { col: 'revenue', kind: 'number' },
      assignedTo: { col: 'assigned_to', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Participants: {
    table: 'participants',
    fields: {
      id: { col: 'id', kind: 'text' },
      fullName: { col: 'full_name', kind: 'text' },
      email: { col: 'email', kind: 'text' },
      phone: { col: 'phone', kind: 'text' },
      idNumber: { col: 'id_number', kind: 'text' },
      city: { col: 'city', kind: 'text' },
      gender: { col: 'gender', kind: 'text' },
      age: { col: 'age', kind: 'number' },
      totalSessions: { col: 'total_sessions', kind: 'number' },
      notes: { col: 'notes', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  RecruitmentRows: {
    table: 'recruitment_rows',
    fields: {
      id: { col: 'id', kind: 'text' },
      rowName: { col: 'row_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      boardName: { col: 'board_name', kind: 'text' },
      participantName: { col: 'participant_name', kind: 'text' },
      email: { col: 'email', kind: 'text' },
      phone: { col: 'phone', kind: 'text' },
      idNumber: { col: 'id_number', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      group: { col: 'group', kind: 'text' },
      parentRowId: { col: 'parent_row_id', kind: 'text' },
      level: { col: 'level', kind: 'number' },
      ndaSent: { col: 'nda_sent', kind: 'boolean' },
      ndaSentDate: { col: 'nda_sent_date', kind: 'datetime' },
      notes: { col: 'notes', kind: 'text' },
      sourceForm: { col: 'source_form', kind: 'text' },
      deletedAt: { col: 'deleted_at', kind: 'text' },
      cellData: { col: 'cell_data', kind: 'text' },
      rowOrder: { col: 'row_order', kind: 'number' },
      boardId: { col: 'board_id', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Suppliers: {
    table: 'suppliers',
    fields: {
      id: { col: 'id', kind: 'text' },
      supplierName: { col: 'supplier_name', kind: 'text' },
      taxId: { col: 'tax_id', kind: 'text' },
      contactName: { col: 'contact_name', kind: 'text' },
      email: { col: 'email', kind: 'text' },
      phone: { col: 'phone', kind: 'text' },
      bankName: { col: 'bank_name', kind: 'text' },
      bankAccount: { col: 'bank_account', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      categories: { col: 'categories', kind: 'array' },
      identifier: { col: 'identifier', kind: 'text' },
      address: { col: 'address', kind: 'text' },
      taxRegime: { col: 'tax_regime', kind: 'text' },
      personType: { col: 'person_type', kind: 'text' },
      country: { col: 'country', kind: 'text' },
      accessToken: { col: 'access_token', kind: 'text' },
      portalPassword: { col: 'portal_password', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  PurchaseOrders: {
    table: 'purchase_orders',
    fields: {
      id: { col: 'id', kind: 'text' },
      poNumber: { col: 'po_number', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      supplierName: { col: 'supplier_name', kind: 'text' },
      issueDate: { col: 'issue_date', kind: 'date' },
      totalAmount: { col: 'total_amount', kind: 'number' },
      status: { col: 'status', kind: 'text' },
      pdfUrl: { col: 'pdf_url', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      category: { col: 'category', kind: 'text' },
      paymentTerms: { col: 'payment_terms', kind: 'text' },
      currency: { col: 'currency', kind: 'text' },
      createdBy: { col: 'created_by', kind: 'text' },
      approvedBy: { col: 'approved_by', kind: 'text' },
      serviceDescription: { col: 'service_description', kind: 'text' },
      billingEntity: { col: 'billing_entity', kind: 'text' },
      emailSentAt: { col: 'email_sent_at', kind: 'datetime' },
      emailSentTo: { col: 'email_sent_to', kind: 'text' },
      tipoDeOc: { col: 'tipo_de_oc', kind: 'text' },
      rejectionReason: { col: 'rejection_reason', kind: 'text' },
      pdfFile: { col: 'pdf_file', kind: 'json' },
      pdfBase64: { col: 'pdf_base64', kind: 'text' },
      origen: { col: 'origen', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  POLineItems: {
    table: 'po_line_items',
    fields: {
      id: { col: 'id', kind: 'text' },
      description: { col: 'description', kind: 'text' },
      poId: { col: 'po_id', kind: 'text' },
      category: { col: 'category', kind: 'text' },
      quantity: { col: 'quantity', kind: 'number' },
      unitPrice: { col: 'unit_price', kind: 'number' },
      total: { col: 'total', kind: 'number' },
      parentItemId: { col: 'parent_item_id', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Tasks: {
    table: 'tasks',
    fields: {
      id: { col: 'id', kind: 'text' },
      taskName: { col: 'task_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      assignedTo: { col: 'assigned_to', kind: 'text' },
      startDate: { col: 'start_date', kind: 'date' },
      endDate: { col: 'end_date', kind: 'date' },
      parentTaskId: { col: 'parent_task_id', kind: 'text' },
      order: { col: 'order', kind: 'number' },
      notes: { col: 'notes', kind: 'text' },
      boardName: { col: 'board_name', kind: 'text' },
      boardId: { col: 'board_id', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  CalendarEvents: {
    table: 'calendar_events',
    fields: {
      id: { col: 'id', kind: 'text' },
      eventName: { col: 'event_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      calendarName: { col: 'calendar_name', kind: 'text' },
      eventDate: { col: 'event_date', kind: 'datetime' },
      durationHours: { col: 'duration_hours', kind: 'number' },
      location: { col: 'location', kind: 'text' },
      attendees: { col: 'attendees', kind: 'text' },
      inviteSent: { col: 'invite_sent', kind: 'boolean' },
      notes: { col: 'notes', kind: 'text' },
      parentEventId: { col: 'parent_event_id', kind: 'text' },
      inviteStatus: { col: 'invite_status', kind: 'text' },
      outlookEventId: { col: 'outlook_event_id', kind: 'text' },
      outlookEventLink: { col: 'outlook_event_link', kind: 'text' },
      inviteBodyHtml: { col: 'invite_body_html', kind: 'text' },
      inviteEmails: { col: 'invite_emails', kind: 'text' },
      boardId: { col: 'board_id', kind: 'text' },
      restringirReenvio: { col: 'restringir_reenvio', kind: 'boolean' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Messages: {
    table: 'messages',
    fields: {
      id: { col: 'id', kind: 'text' },
      messageId: { col: 'message_id', kind: 'number' },
      channel: { col: 'channel', kind: 'text' },
      senderName: { col: 'sender_name', kind: 'text' },
      senderEmail: { col: 'sender_email', kind: 'text' },
      content: { col: 'content', kind: 'text' },
      sentAt: { col: 'sent_at', kind: 'datetime' },
      parentMessageId: { col: 'parent_message_id', kind: 'text' },
      reactions: { col: 'reactions', kind: 'text' },
      pinned: { col: 'pinned', kind: 'boolean' },
      attachments: { col: 'attachments', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  BoardColumns: {
    table: 'board_columns',
    fields: {
      id: { col: 'id', kind: 'text' },
      columnName: { col: 'column_name', kind: 'text' },
      boardId: { col: 'board_id', kind: 'text' },
      columnType: { col: 'column_type', kind: 'text' },
      optionsJson: { col: 'options_json', kind: 'text' },
      columnOrder: { col: 'column_order', kind: 'number' },
      deletedAt: { col: 'deleted_at', kind: 'text' },
      deletedBy: { col: 'deleted_by', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  CellValues: {
    table: 'cell_values',
    conflictTarget: { cols: ['board_id', 'row_id', 'column_id'], where: 'deleted_at is null' },
    fields: {
      id: { col: 'id', kind: 'text' },
      cellId: { col: 'cell_id', kind: 'number' },
      boardId: { col: 'board_id', kind: 'text' },
      rowId: { col: 'row_id', kind: 'text' },
      columnId: { col: 'column_id', kind: 'text' },
      textValue: { col: 'text_value', kind: 'text' },
      numberValue: { col: 'number_value', kind: 'number' },
      dateValue: { col: 'date_value', kind: 'datetime' },
      booleanValue: { col: 'boolean_value', kind: 'boolean' },
      fileUrl: { col: 'file_url', kind: 'text' },
      deletedAt: { col: 'deleted_at', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Invoices: {
    table: 'invoices',
    fields: {
      id: { col: 'id', kind: 'text' },
      invoiceNumber: { col: 'invoice_number', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      client: { col: 'client', kind: 'text' },
      type: { col: 'type', kind: 'text' },
      amount: { col: 'amount', kind: 'number' },
      currency: { col: 'currency', kind: 'text' },
      issueDate: { col: 'issue_date', kind: 'date' },
      dueDate: { col: 'due_date', kind: 'date' },
      status: { col: 'status', kind: 'text' },
      pdfUrl: { col: 'pdf_url', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Payments: {
    table: 'payments',
    fields: {
      id: { col: 'id', kind: 'text' },
      paymentId: { col: 'payment_id', kind: 'number' },
      poId: { col: 'po_id', kind: 'text' },
      invoiceId: { col: 'invoice_id', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      type: { col: 'type', kind: 'text' },
      amount: { col: 'amount', kind: 'number' },
      paymentDate: { col: 'payment_date', kind: 'date' },
      method: { col: 'method', kind: 'text' },
      reference: { col: 'reference', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      supplierName: { col: 'supplier_name', kind: 'text' },
      currency: { col: 'currency', kind: 'text' },
      attachment: { col: 'attachment', kind: 'json' },
      dueDate: { col: 'due_date', kind: 'date' },
      supplierInvoiceNumber: { col: 'supplier_invoice_number', kind: 'text' },
      destinationAccount: { col: 'destination_account', kind: 'text' },
      sourceCompany: { col: 'source_company', kind: 'text' },
      sourceBank: { col: 'source_bank', kind: 'text' },
      sourceAccount: { col: 'source_account', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Documents: {
    table: 'documents',
    fields: {
      id: { col: 'id', kind: 'text' },
      documentName: { col: 'document_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      category: { col: 'category', kind: 'text' },
      fileUrl: { col: 'file_url', kind: 'text' },
      uploadedBy: { col: 'uploaded_by', kind: 'text' },
      uploadDate: { col: 'upload_date', kind: 'date' },
      version: { col: 'version', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Boards: {
    table: 'boards',
    fields: {
      id: { col: 'id', kind: 'text' },
      boardName: { col: 'board_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      boardOrder: { col: 'board_order', kind: 'number' },
      deletedAt: { col: 'deleted_at', kind: 'datetime' },
      boardType: { col: 'board_type', kind: 'text' },
      excelColumnsJson: { col: 'excel_columns_json', kind: 'text' },
      calendarVersion: { col: 'calendar_version', kind: 'number' },
      calendarFileUrl: { col: 'calendar_file_url', kind: 'text' },
      timelineVersion: { col: 'timeline_version', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  SharedViews: {
    table: 'shared_views',
    fields: {
      id: { col: 'id', kind: 'text' },
      viewName: { col: 'view_name', kind: 'text' },
      boardId: { col: 'board_id', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      boardName: { col: 'board_name', kind: 'text' },
      token: { col: 'token', kind: 'text' },
      filtersJson: { col: 'filters_json', kind: 'text' },
      visibleColumnsJson: { col: 'visible_columns_json', kind: 'text' },
      createdBy: { col: 'created_by', kind: 'text' },
      active: { col: 'active', kind: 'boolean' },
      type: { col: 'type', kind: 'text' },
      sharedToken: { col: 'shared_token', kind: 'text' },
      viewOrder: { col: 'view_order', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  ChatConversations: {
    table: 'chat_conversations',
    fields: {
      id: { col: 'id', kind: 'text' },
      conversationName: { col: 'conversation_name', kind: 'text' },
      type: { col: 'type', kind: 'text' },
      members: { col: 'members', kind: 'text' },
      createdBy: { col: 'created_by', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      lastMessageAt: { col: 'last_message_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  BillingEntities: {
    table: 'billing_entities',
    fields: {
      id: { col: 'id', kind: 'text' },
      companyName: { col: 'company_name', kind: 'text' },
      rfc: { col: 'rfc', kind: 'text' },
      address: { col: 'address', kind: 'text' },
      postalCode: { col: 'postal_code', kind: 'text' },
      city: { col: 'city', kind: 'text' },
      state: { col: 'state', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  SupplierInvoices: {
    table: 'supplier_invoices',
    fields: {
      id: { col: 'id', kind: 'text' },
      invoiceNumber: { col: 'invoice_number', kind: 'text' },
      poId: { col: 'po_id', kind: 'text' },
      supplierId: { col: 'supplier_id', kind: 'text' },
      supplierName: { col: 'supplier_name', kind: 'text' },
      poNumber: { col: 'po_number', kind: 'text' },
      amount: { col: 'amount', kind: 'number' },
      currency: { col: 'currency', kind: 'text' },
      pdfFile: { col: 'pdf_file', kind: 'json' },
      xmlFile: { col: 'xml_file', kind: 'json' },
      supportFile: { col: 'support_file', kind: 'json' },
      status: { col: 'status', kind: 'text' },
      uploadDate: { col: 'upload_date', kind: 'datetime' },
      uploadedBy: { col: 'uploaded_by', kind: 'text' },
      reviewNotes: { col: 'review_notes', kind: 'text' },
      reviewedBy: { col: 'reviewed_by', kind: 'text' },
      reviewedAt: { col: 'reviewed_at', kind: 'datetime' },
      projectCode: { col: 'project_code', kind: 'text' },
      supplierComment: { col: 'supplier_comment', kind: 'text' },
      subtotal: { col: 'subtotal', kind: 'number' },
      ivaRate: { col: 'iva_rate', kind: 'number' },
      ivaAmount: { col: 'iva_amount', kind: 'number' },
      retencionIva: { col: 'retencion_iva', kind: 'number' },
      retencionIsr: { col: 'retencion_isr', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  ApprovalLimits: {
    table: 'approval_limits',
    fields: {
      id: { col: 'id', kind: 'text' },
      limitId: { col: 'limit_id', kind: 'number' },
      costCenter: { col: 'cost_center', kind: 'text' },
      approvalLevel: { col: 'approval_level', kind: 'text' },
      maxAmount: { col: 'max_amount', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  POAuditLog: {
    table: 'po_audit_logs',
    fields: {
      id: { col: 'id', kind: 'text' },
      timestamp: { col: 'timestamp', kind: 'datetime' },
      purchaseOrder: { col: 'purchase_order_id', kind: 'link', target: 'purchase_orders' },
      action: { col: 'action', kind: 'text' },
      userEmail: { col: 'user_email', kind: 'text' },
      userName: { col: 'user_name', kind: 'text' },
      comments: { col: 'comments', kind: 'text' },
      poNumber: { col: 'po_number', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  PoAttachments: {
    table: 'po_attachments',
    fields: {
      id: { col: 'id', kind: 'text' },
      name: { col: 'name', kind: 'text' },
      purchaseOrder: { col: 'purchase_order_id', kind: 'link', target: 'purchase_orders' },
      fileUrl: { col: 'file_url', kind: 'text' },
      description: { col: 'description', kind: 'text' },
      uploadedByEmail: { col: 'uploaded_by_email', kind: 'text' },
      uploadedByName: { col: 'uploaded_by_name', kind: 'text' },
      uploadedAt: { col: 'uploaded_at', kind: 'datetime' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  AppSettings: {
    table: 'app_settings',
    fields: {
      id: { col: 'id', kind: 'text' },
      settingKey: { col: 'setting_key', kind: 'text' },
      defaultVisiblePages: { col: 'default_visible_pages', kind: 'array' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Deals: {
    table: 'deals',
    fields: {
      id: { col: 'id', kind: 'text' },
      dealName: { col: 'deal_name', kind: 'text' },
      phase: { col: 'phase', kind: 'text' },
      client: { col: 'client', kind: 'text' },
      projectType: { col: 'project_type', kind: 'text' },
      tematica: { col: 'tematica', kind: 'text' },
      owner: { col: 'owner_id', kind: 'link', target: 'users' },
      proposalDate: { col: 'proposal_date', kind: 'date' },
      approvalDate: { col: 'approval_date', kind: 'date' },
      currency: { col: 'currency', kind: 'text' },
      clientPrice: { col: 'client_price', kind: 'number' },
      taxesPct: { col: 'taxes_pct', kind: 'number' },
      quotedCost: { col: 'quoted_cost', kind: 'number' },
      notes: { col: 'notes', kind: 'text' },
      retenciones: { col: 'retenciones', kind: 'number' },
      empresaOperadora: { col: 'empresa_operadora', kind: 'text' },
      puntoDeContacto: { col: 'punto_de_contacto', kind: 'text' },
      statusPropuesta: { col: 'status_propuesta', kind: 'text' },
      hechaPor: { col: 'hecha_por', kind: 'text' },
      fechaDeBrief: { col: 'fecha_de_brief', kind: 'date' },
      fechaPerdida: { col: 'fecha_perdida', kind: 'date' },
      gerente: { col: 'gerente', kind: 'text' },
      exchangeRate: { col: 'exchange_rate', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Cotizaciones: {
    table: 'cotizaciones',
    fields: {
      id: { col: 'id', kind: 'text' },
      cotizacionName: { col: 'cotizacion_name', kind: 'text' },
      deal: { col: 'deal_id', kind: 'link', target: 'deals' },
      status: { col: 'status', kind: 'text' },
      currency: { col: 'currency', kind: 'text' },
      totalCost: { col: 'total_cost', kind: 'number' },
      clientPrice: { col: 'client_price', kind: 'number' },
      notes: { col: 'notes', kind: 'text' },
      included: { col: 'included', kind: 'boolean' },
      createdBy: { col: 'created_by_id', kind: 'link', target: 'users' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  CotizacionLineItems: {
    table: 'cotizacion_line_items',
    fields: {
      id: { col: 'id', kind: 'text' },
      subRubro: { col: 'sub_rubro', kind: 'text' },
      cotizacion: { col: 'cotizacion_id', kind: 'link', target: 'cotizaciones' },
      rubro: { col: 'rubro', kind: 'text' },
      cantidad: { col: 'cantidad', kind: 'number' },
      unitCost: { col: 'unit_cost', kind: 'number' },
      hasMarkup: { col: 'has_markup', kind: 'boolean' },
      markupPct: { col: 'markup_pct', kind: 'number' },
      finalPrice: { col: 'final_price', kind: 'number' },
      componentes: { col: 'componentes', kind: 'number' },
      includedInBudget: { col: 'included_in_budget', kind: 'boolean' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  DealDocuments: {
    table: 'deal_documents',
    fields: {
      id: { col: 'id', kind: 'text' },
      documentName: { col: 'document_name', kind: 'text' },
      deal: { col: 'deal_id', kind: 'link', target: 'deals' },
      docType: { col: 'doc_type', kind: 'text' },
      version: { col: 'version', kind: 'text' },
      fileUrl: { col: 'file_url', kind: 'text' },
      fileName: { col: 'file_name', kind: 'text' },
      uploadDate: { col: 'upload_date', kind: 'date' },
      notes: { col: 'notes', kind: 'text' },
      content: { col: 'content', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  DocumentBlocks: {
    table: 'document_blocks',
    fields: {
      id: { col: 'id', kind: 'text' },
      blockId: { col: 'block_id', kind: 'number' },
      blockContent: { col: 'block_content', kind: 'text' },
      blockType: { col: 'block_type', kind: 'text' },
      authorName: { col: 'author_name', kind: 'text' },
      authorEmail: { col: 'author_email', kind: 'text' },
      deal: { col: 'deal_id', kind: 'link', target: 'deals' },
      sortOrder: { col: 'sort_order', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' },
      checklistData: { col: 'checklist_data', kind: 'text' },
      documentJson: { col: 'document_json', kind: 'text' }
    },
  },
  PettyCashFunds: {
    table: 'petty_cash_funds',
    fields: {
      id: { col: 'id', kind: 'text' },
      fundName: { col: 'fund_name', kind: 'text' },
      initialAmount: { col: 'initial_amount', kind: 'number' },
      currentBalance: { col: 'current_balance', kind: 'number' },
      costCenter: { col: 'cost_center', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      lastReplenishmentDate: { col: 'last_replenishment_date', kind: 'date' },
      notes: { col: 'notes', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  Expenses: {
    table: 'expenses',
    fields: {
      id: { col: 'id', kind: 'text' },
      expenseNumber: { col: 'expense_number', kind: 'number' },
      description: { col: 'description', kind: 'text' },
      amount: { col: 'amount', kind: 'number' },
      category: { col: 'category', kind: 'text' },
      paymentMethod: { col: 'payment_method', kind: 'text' },
      costCenter: { col: 'cost_center', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      currency: { col: 'currency', kind: 'text' },
      expenseDate: { col: 'expense_date', kind: 'date' },
      status: { col: 'status', kind: 'text' },
      receipt: { col: 'receipt', kind: 'json' },
      notes: { col: 'notes', kind: 'text' },
      createdBy: { col: 'created_by', kind: 'text' },
      approvedBy: { col: 'approved_by', kind: 'text' },
      rejectionReason: { col: 'rejection_reason', kind: 'text' },
      pettyCashFund: { col: 'petty_cash_fund_id', kind: 'link', target: 'petty_cash_funds' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  ExpenseAuditLog: {
    table: 'expense_audit_logs',
    fields: {
      id: { col: 'id', kind: 'text' },
      timestamp: { col: 'timestamp', kind: 'text' },
      expense: { col: 'expense_id', kind: 'link', target: 'expenses' },
      action: { col: 'action', kind: 'text' },
      userEmail: { col: 'user_email', kind: 'text' },
      userName: { col: 'user_name', kind: 'text' },
      comments: { col: 'comments', kind: 'text' },
      expenseNumber: { col: 'expense_number', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  ExpenseComments: {
    table: 'expense_comments',
    fields: {
      id: { col: 'id', kind: 'text' },
      comment: { col: 'comment', kind: 'text' },
      expense: { col: 'expense_id', kind: 'link', target: 'expenses' },
      authorEmail: { col: 'author_email', kind: 'text' },
      authorName: { col: 'author_name', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  TaskComments: {
    table: 'task_comments',
    fields: {
      id: { col: 'id', kind: 'text' },
      taskId: { col: 'task_id', kind: 'text' },
      messageId: { col: 'message_id', kind: 'text' },
      taskName: { col: 'task_name', kind: 'text' },
      channel: { col: 'channel', kind: 'text' },
      senderName: { col: 'sender_name', kind: 'text' },
      senderEmail: { col: 'sender_email', kind: 'text' },
      content: { col: 'content', kind: 'text' },
      sentAt: { col: 'sent_at', kind: 'datetime' },
      isThreadReply: { col: 'is_thread_reply', kind: 'boolean' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  ExpenseLineItems: {
    table: 'expense_line_items',
    fields: {
      id: { col: 'id', kind: 'text' },
      description: { col: 'description', kind: 'text' },
      expense: { col: 'expense_id', kind: 'link', target: 'expenses' },
      category: { col: 'category', kind: 'text' },
      amount: { col: 'amount', kind: 'number' },
      date: { col: 'date', kind: 'date' },
      receipt: { col: 'receipt', kind: 'json' },
      notes: { col: 'notes', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  CommercialDashboardViews: {
    table: 'commercial_dashboard_views',
    fields: {
      id: { col: 'id', kind: 'text' },
      viewName: { col: 'view_name', kind: 'text' },
      viewId: { col: 'view_id', kind: 'text' },
      owner: { col: 'owner_id', kind: 'link', target: 'users' },
      isDefault: { col: 'is_default', kind: 'boolean' },
      isShared: { col: 'is_shared', kind: 'boolean' },
      filtersJson: { col: 'filters_json', kind: 'text' },
      widgetsJson: { col: 'widgets_json', kind: 'text' },
      dateReference: { col: 'date_reference', kind: 'text' },
      sortOrder: { col: 'sort_order', kind: 'number' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  CalendarAuditLog: {
    table: 'calendar_audit_logs',
    fields: {
      id: { col: 'id', kind: 'text' },
      action: { col: 'action', kind: 'text' },
      eventName: { col: 'event_name', kind: 'text' },
      calendarName: { col: 'calendar_name', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      userEmail: { col: 'user_email', kind: 'text' },
      userName: { col: 'user_name', kind: 'text' },
      timestamp: { col: 'timestamp', kind: 'datetime' },
      details: { col: 'details', kind: 'text' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  CollectionProcesses: {
    table: 'collection_processes',
    fields: {
      id: { col: 'id', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      deal: { col: 'deal_id', kind: 'link', target: 'deals' },
      client: { col: 'client', kind: 'text' },
      currency: { col: 'currency', kind: 'text' },
      quotedAmount: { col: 'quoted_amount', kind: 'number' },
      collectionAmount: { col: 'collection_amount', kind: 'number' },
      phase: { col: 'phase', kind: 'text' },
      applicablePhases: { col: 'applicable_phases', kind: 'text' },
      proformaCreatedAt: { col: 'proforma_created_at', kind: 'datetime' },
      proformaSentAt: { col: 'proforma_sent_at', kind: 'datetime' },
      invoiceCreatedAt: { col: 'invoice_created_at', kind: 'datetime' },
      invoiceSentAt: { col: 'invoice_sent_at', kind: 'datetime' },
      portalUploadedAt: { col: 'portal_uploaded_at', kind: 'datetime' },
      grMigoAt: { col: 'gr_migo_at', kind: 'datetime' },
      scheduledPaymentDate: { col: 'scheduled_payment_date', kind: 'date' },
      paidAt: { col: 'paid_at', kind: 'date' },
      invoiceNumber: { col: 'invoice_number', kind: 'text' },
      status: { col: 'status', kind: 'text' },
      notes: { col: 'notes', kind: 'text' },
      responsibleUser: { col: 'responsible_user_id', kind: 'link', target: 'users' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  RubroAssignments: {
    table: 'rubro_assignments',
    fields: {
      id: { col: 'id', kind: 'text' },
      rubro: { col: 'rubro', kind: 'text' },
      assignedUser: { col: 'assigned_user_id', kind: 'link', target: 'users' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
  MigrationLog: {
    table: 'migration_logs',
    fields: {
      id: { col: 'id', kind: 'text' },
      projectCode: { col: 'project_code', kind: 'text' },
      boardId: { col: 'board_id', kind: 'text' },
      migrated: { col: 'migrated', kind: 'number' },
      failed: { col: 'failed', kind: 'number' },
      skipped: { col: 'skipped', kind: 'number' },
      status: { col: 'status', kind: 'text' },
      durationSeconds: { col: 'duration_seconds', kind: 'number' },
      runBy: { col: 'run_by_id', kind: 'link', target: 'users' },
      createdAt: { col: 'created_at', kind: 'datetime' },
      updatedAt: { col: 'updated_at', kind: 'datetime' }
    },
  },
};

export const MODEL_NAMES = Object.keys(SCHEMA) as (keyof typeof SCHEMA)[];