-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

SET check_function_bodies = false;

DROP EXTENSION pg_net;

CREATE EXTENSION pg_trgm WITH SCHEMA public;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
begin new.updated_at = now(); return new; end;
$function$;

GRANT ALL ON FUNCTION public.set_updated_at() TO anon;

GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;

GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;

CREATE TABLE public.app_settings (
  id                    uuid                     DEFAULT gen_random_uuid() NOT NULL,
  setting_key           text,
  default_visible_pages text[],
  created_at            timestamp with time zone DEFAULT now() NOT NULL,
  updated_at            timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.app_settings
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.app_settings
  ADD CONSTRAINT app_settings_default_visible_pages_chk
    CHECK
    (default_visible_pages IS NULL OR default_visible_pages <@ ARRAY['Dashboard'::text, 'Chat'::text, 'CRM / Deals'::text, 'Dashboard comercial'::text, 'Proyectos'::text,
    'Órdenes de compra'::text,
    'Proveedores'::text,
    'Pagos a proveedores'::text, 'Facturas de proveedores'::text, 'Cobranza'::text, 'Costos por proyecto'::text, 'Dashboard financiero'::text, 'Tableros flexibles'::text]);

ALTER TABLE public.app_settings
  ADD CONSTRAINT app_settings_pkey PRIMARY KEY (id);

GRANT ALL ON public.app_settings TO anon;

GRANT ALL ON public.app_settings TO authenticated;

GRANT ALL ON public.app_settings TO service_role;

CREATE TRIGGER app_settings_set_updated
  BEFORE UPDATE ON public.app_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.approval_limits (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  limit_id       bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cost_center    text,
  approval_level text,
  max_amount     numeric(14,2),
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.approval_limits
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.approval_limits
  ADD CONSTRAINT approval_limits_approval_level_chk CHECK (approval_level IS NULL OR (approval_level = ANY (ARRAY['Área'::text, 'Finanzas'::text])));

ALTER TABLE public.approval_limits
  ADD CONSTRAINT approval_limits_cost_center_chk
    CHECK (cost_center IS NULL OR (cost_center = ANY (ARRAY['Reclutamiento e Incentivos'::text, 'Logística'::text, 'Moderaciones'::text, 'Management'::text, 'Otros'::text])));

ALTER TABLE public.approval_limits
  ADD CONSTRAINT approval_limits_pkey PRIMARY KEY (id);

GRANT ALL ON public.approval_limits TO anon;

GRANT ALL ON public.approval_limits TO authenticated;

GRANT ALL ON public.approval_limits TO service_role;

CREATE TRIGGER approval_limits_set_updated
  BEFORE UPDATE ON public.approval_limits
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.billing_entities (
  id           uuid                     DEFAULT gen_random_uuid() NOT NULL,
  company_name text,
  rfc          text,
  address      text,
  postal_code  text,
  city         text,
  state        text,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at   timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.billing_entities
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.billing_entities
  ADD CONSTRAINT billing_entities_pkey PRIMARY KEY (id);

GRANT ALL ON public.billing_entities TO anon;

GRANT ALL ON public.billing_entities TO authenticated;

GRANT ALL ON public.billing_entities TO service_role;

CREATE TRIGGER billing_entities_set_updated
  BEFORE UPDATE ON public.billing_entities
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.board_columns (
  id           uuid                     DEFAULT gen_random_uuid() NOT NULL,
  column_name  text,
  board_id     text,
  column_type  text,
  options_json text,
  column_order numeric,
  deleted_at   text,
  deleted_by   text,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at   timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.board_columns
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.board_columns
  ADD CONSTRAINT board_columns_pkey PRIMARY KEY (id);

GRANT ALL ON public.board_columns TO anon;

GRANT ALL ON public.board_columns TO authenticated;

GRANT ALL ON public.board_columns TO service_role;

CREATE INDEX board_columns_column_type_idx ON public.board_columns (column_type);

CREATE INDEX board_columns_board_id_idx ON public.board_columns (board_id);

CREATE TRIGGER board_columns_set_updated
  BEFORE UPDATE ON public.board_columns
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.board_columns_backup (
  id           uuid,
  column_name  text,
  board_id     text,
  column_type  text,
  options_json text,
  column_order numeric,
  deleted_at   text,
  deleted_by   text,
  created_at   timestamp with time zone,
  updated_at   timestamp with time zone
);

ALTER TABLE public.board_columns_backup
  ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.board_columns_backup TO anon;

GRANT ALL ON public.board_columns_backup TO authenticated;

GRANT ALL ON public.board_columns_backup TO service_role;

CREATE TABLE public.boards (
  id                 uuid                     DEFAULT gen_random_uuid() NOT NULL,
  board_name         text,
  project_code       text,
  board_order        numeric,
  deleted_at         timestamp with time zone,
  board_type         text,
  excel_columns_json text,
  calendar_version   numeric,
  calendar_file_url  text,
  timeline_version   numeric,
  created_at         timestamp with time zone DEFAULT now() NOT NULL,
  updated_at         timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.boards
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.boards
  ADD CONSTRAINT boards_pkey PRIMARY KEY (id);

GRANT ALL ON public.boards TO anon;

GRANT ALL ON public.boards TO authenticated;

GRANT ALL ON public.boards TO service_role;

CREATE INDEX boards_project_code_idx ON public.boards (project_code);

CREATE INDEX boards_board_type_idx ON public.boards (board_type);

CREATE INDEX boards_board_name_idx ON public.boards (board_name);

CREATE TRIGGER boards_set_updated
  BEFORE UPDATE ON public.boards
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.calendar_audit_logs (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  action        text,
  event_name    text,
  calendar_name text,
  project_code  text,
  user_email    text,
  user_name     text,
  "timestamp"   timestamp with time zone,
  details       text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.calendar_audit_logs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.calendar_audit_logs
  ADD CONSTRAINT calendar_audit_logs_pkey PRIMARY KEY (id);

GRANT ALL ON public.calendar_audit_logs TO anon;

GRANT ALL ON public.calendar_audit_logs TO authenticated;

GRANT ALL ON public.calendar_audit_logs TO service_role;

CREATE TRIGGER calendar_audit_logs_set_updated
  BEFORE UPDATE ON public.calendar_audit_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.calendar_events (
  id                 uuid                     DEFAULT gen_random_uuid() NOT NULL,
  event_name         text,
  project_code       text,
  calendar_name      text,
  event_date         timestamp with time zone,
  duration_hours     numeric,
  location           text,
  attendees          text,
  invite_sent        boolean,
  notes              text,
  parent_event_id    text,
  invite_status      text,
  outlook_event_id   text,
  outlook_event_link text,
  invite_body_html   text,
  invite_emails      text,
  board_id           text,
  restringir_reenvio boolean,
  created_at         timestamp with time zone DEFAULT now() NOT NULL,
  updated_at         timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.calendar_events
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.calendar_events
  ADD CONSTRAINT calendar_events_invite_status_chk
    CHECK (invite_status IS NULL OR (invite_status = ANY (ARRAY['Por crear'::text, 'Por actualizar'::text, 'Por cancelar'::text, 'Enviado'::text, 'Cancelado'::text])));

ALTER TABLE public.calendar_events
  ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id);

GRANT ALL ON public.calendar_events TO anon;

GRANT ALL ON public.calendar_events TO authenticated;

GRANT ALL ON public.calendar_events TO service_role;

CREATE INDEX calendar_events_project_code_idx ON public.calendar_events (project_code);

CREATE TRIGGER calendar_events_set_updated
  BEFORE UPDATE ON public.calendar_events
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.cell_values (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  cell_id       bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  board_id      text,
  row_id        text,
  column_id     text,
  text_value    text,
  number_value  numeric,
  date_value    timestamp with time zone,
  boolean_value boolean,
  file_url      text,
  deleted_at    text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.cell_values
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cell_values
  ADD CONSTRAINT cell_values_pkey PRIMARY KEY (id);

GRANT ALL ON public.cell_values TO anon;

GRANT ALL ON public.cell_values TO authenticated;

GRANT ALL ON public.cell_values TO service_role;

CREATE INDEX cell_values_board_id_idx ON public.cell_values (board_id);

CREATE UNIQUE INDEX cell_values_posicion_viva_uniq ON public.cell_values (board_id, row_id, column_id)
  WHERE deleted_at IS NULL;

CREATE INDEX cell_values_board_id_row_id_column_id_idx ON public.cell_values (board_id, row_id, column_id);

CREATE INDEX cell_values_row_id_idx ON public.cell_values (row_id);

CREATE TRIGGER cell_values_set_updated
  BEFORE UPDATE ON public.cell_values
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.cell_values_backup (
  id            uuid,
  cell_id       bigint,
  board_id      text,
  row_id        text,
  column_id     text,
  text_value    text,
  number_value  numeric,
  date_value    timestamp with time zone,
  boolean_value boolean,
  file_url      text,
  deleted_at    text,
  created_at    timestamp with time zone,
  updated_at    timestamp with time zone
);

ALTER TABLE public.cell_values_backup
  ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.cell_values_backup TO anon;

GRANT ALL ON public.cell_values_backup TO authenticated;

GRANT ALL ON public.cell_values_backup TO service_role;

CREATE TABLE public.chat_conversations (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  conversation_name text,
  type              text,
  members           text,
  created_by        text,
  created_at        timestamp with time zone,
  last_message_at   timestamp with time zone,
  updated_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.chat_conversations
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.chat_conversations
  ADD CONSTRAINT chat_conversations_pkey PRIMARY KEY (id);

ALTER TABLE public.chat_conversations
  ADD CONSTRAINT chat_conversations_type_chk CHECK (type IS NULL OR (type = ANY (ARRAY['DM'::text, 'Group'::text])));

GRANT ALL ON public.chat_conversations TO anon;

GRANT ALL ON public.chat_conversations TO authenticated;

GRANT ALL ON public.chat_conversations TO service_role;

CREATE TRIGGER chat_conversations_set_updated
  BEFORE UPDATE ON public.chat_conversations
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.collection_processes (
  id                     uuid                     DEFAULT gen_random_uuid() NOT NULL,
  project_code           text,
  deal_id                uuid,
  client                 text,
  currency               text,
  quoted_amount          numeric(14,2),
  collection_amount      numeric(14,2),
  phase                  text,
  applicable_phases      text,
  proforma_created_at    timestamp with time zone,
  proforma_sent_at       timestamp with time zone,
  invoice_created_at     timestamp with time zone,
  invoice_sent_at        timestamp with time zone,
  portal_uploaded_at     timestamp with time zone,
  gr_migo_at             timestamp with time zone,
  scheduled_payment_date date,
  paid_at                date,
  invoice_number         text,
  status                 text,
  notes                  text,
  responsible_user_id    uuid,
  created_at             timestamp with time zone DEFAULT now() NOT NULL,
  updated_at             timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.collection_processes
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.collection_processes
  ADD CONSTRAINT collection_processes_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text, 'EUR'::text])));

ALTER TABLE public.collection_processes
  ADD CONSTRAINT collection_processes_phase_chk
    CHECK
    (phase IS NULL OR (phase = ANY (ARRAY['Por iniciar'::text, 'Proforma creada'::text, 'Proforma enviada'::text, 'Factura creada'::text, 'Factura enviada'::text,
    'Subida al portal'::text, 'GR / Migo'::text, 'Cobranza programada'::text, 'Pagada'::text, 'Atrasada'::text])));

ALTER TABLE public.collection_processes
  ADD CONSTRAINT collection_processes_pkey PRIMARY KEY (id);

ALTER TABLE public.collection_processes
  ADD CONSTRAINT collection_processes_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Al día'::text, 'Atrasado'::text, 'Pagado'::text])));

GRANT ALL ON public.collection_processes TO anon;

GRANT ALL ON public.collection_processes TO authenticated;

GRANT ALL ON public.collection_processes TO service_role;

CREATE TRIGGER collection_processes_set_updated
  BEFORE UPDATE ON public.collection_processes
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.commercial_dashboard_views (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  view_name      text,
  view_id        text,
  owner_id       uuid,
  is_default     boolean,
  is_shared      boolean,
  filters_json   text,
  widgets_json   text,
  date_reference text,
  sort_order     numeric,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.commercial_dashboard_views
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.commercial_dashboard_views
  ADD CONSTRAINT commercial_dashboard_views_date_reference_chk
    CHECK (date_reference IS NULL OR (date_reference = ANY (ARRAY['Fecha de propuesta'::text, 'Fecha de aprobación'::text])));

ALTER TABLE public.commercial_dashboard_views
  ADD CONSTRAINT commercial_dashboard_views_pkey PRIMARY KEY (id);

GRANT ALL ON public.commercial_dashboard_views TO anon;

GRANT ALL ON public.commercial_dashboard_views TO authenticated;

GRANT ALL ON public.commercial_dashboard_views TO service_role;

CREATE TRIGGER commercial_dashboard_views_set_updated
  BEFORE UPDATE ON public.commercial_dashboard_views
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.cotizacion_line_items (
  id                 uuid                     DEFAULT gen_random_uuid() NOT NULL,
  sub_rubro          text,
  cotizacion_id      uuid,
  rubro              text,
  cantidad           numeric,
  unit_cost          numeric(14,2),
  has_markup         boolean,
  markup_pct         numeric(6,4),
  final_price        numeric(14,2),
  componentes        numeric,
  included_in_budget boolean,
  created_at         timestamp with time zone DEFAULT now() NOT NULL,
  updated_at         timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.cotizacion_line_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cotizacion_line_items
  ADD CONSTRAINT cotizacion_line_items_pkey PRIMARY KEY (id);

ALTER TABLE public.cotizacion_line_items
  ADD CONSTRAINT cotizacion_line_items_rubro_chk
    CHECK (rubro IS NULL OR (rubro = ANY (ARRAY['Reclutamiento e incentivos'::text, 'Moderación'::text, 'Management'::text, 'Logística y operación'::text, 'Back office'::text])));

GRANT ALL ON public.cotizacion_line_items TO anon;

GRANT ALL ON public.cotizacion_line_items TO authenticated;

GRANT ALL ON public.cotizacion_line_items TO service_role;

CREATE TRIGGER cotizacion_line_items_set_updated
  BEFORE UPDATE ON public.cotizacion_line_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.cotizaciones (
  id              uuid                     DEFAULT gen_random_uuid() NOT NULL,
  cotizacion_name text,
  deal_id         uuid,
  status          text,
  currency        text,
  total_cost      numeric(14,2),
  client_price    numeric(14,2),
  notes           text,
  included        boolean,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.cotizaciones
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cotizaciones
  ADD CONSTRAINT cotizaciones_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text, 'EUR'::text])));

ALTER TABLE public.cotizaciones
  ADD CONSTRAINT cotizaciones_pkey PRIMARY KEY (id);

ALTER TABLE public.cotizacion_line_items
  ADD CONSTRAINT cotizacion_line_items_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id) ON DELETE SET NULL;

ALTER TABLE public.cotizaciones
  ADD CONSTRAINT cotizaciones_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Borrador'::text, 'Enviada'::text, 'Aprobada'::text, 'Rechazada'::text])));

GRANT ALL ON public.cotizaciones TO anon;

GRANT ALL ON public.cotizaciones TO authenticated;

GRANT ALL ON public.cotizaciones TO service_role;

CREATE TRIGGER cotizaciones_set_updated
  BEFORE UPDATE ON public.cotizaciones
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.crm_items (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  item_name     text,
  project_code  text,
  client        text,
  status        text,
  proposal_date date,
  contract_date date,
  budget        numeric(14,2),
  revenue       numeric(14,2),
  assigned_to   text,
  notes         text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.crm_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.crm_items
  ADD CONSTRAINT crm_items_pkey PRIMARY KEY (id);

ALTER TABLE public.crm_items
  ADD CONSTRAINT crm_items_status_chk
    CHECK (status IS NULL OR (status = ANY (ARRAY['Prospecto'::text, 'Propuesta enviada'::text, 'Negociación'::text, 'Ganado'::text, 'Perdido'::text])));

GRANT ALL ON public.crm_items TO anon;

GRANT ALL ON public.crm_items TO authenticated;

GRANT ALL ON public.crm_items TO service_role;

CREATE TRIGGER crm_items_set_updated
  BEFORE UPDATE ON public.crm_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.deal_documents (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  document_name text,
  deal_id       uuid,
  doc_type      text,
  version       text,
  file_url      text,
  file_name     text,
  upload_date   date,
  notes         text,
  content       text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.deal_documents
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.deal_documents
  ADD CONSTRAINT deal_documents_doc_type_chk
    CHECK
    (doc_type IS NULL OR (doc_type = ANY (ARRAY['Brief de cliente'::text, 'Notas de brief'::text, 'Solicitud de cambios'::text, 'Propuesta PPT'::text, 'Propuesta PDF'::text,
    'Otro'::text])));

ALTER TABLE public.deal_documents
  ADD CONSTRAINT deal_documents_pkey PRIMARY KEY (id);

GRANT ALL ON public.deal_documents TO anon;

GRANT ALL ON public.deal_documents TO authenticated;

GRANT ALL ON public.deal_documents TO service_role;

CREATE TRIGGER deal_documents_set_updated
  BEFORE UPDATE ON public.deal_documents
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.deals (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  deal_name         text,
  phase             text,
  client            text,
  project_type      text,
  tematica          text,
  owner_id          uuid,
  proposal_date     date,
  approval_date     date,
  currency          text,
  client_price      numeric(14,2),
  taxes_pct         numeric(6,4),
  quoted_cost       numeric(14,2),
  notes             text,
  retenciones       numeric(6,4),
  empresa_operadora text,
  punto_de_contacto text,
  status_propuesta  text,
  hecha_por         text,
  fecha_de_brief    date,
  fecha_perdida     date,
  gerente           text,
  exchange_rate     numeric,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  updated_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.deals
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.deals
  ADD CONSTRAINT deals_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN 🇲🇽'::text, 'USD 🇺🇸'::text, 'EUR 🇪🇺'::text])));

ALTER TABLE public.deals
  ADD CONSTRAINT deals_empresa_operadora_chk CHECK (empresa_operadora IS NULL OR (empresa_operadora = ANY (ARRAY['AGC'::text, 'EME'::text])));

ALTER TABLE public.deals
  ADD CONSTRAINT deals_phase_chk
    CHECK (phase IS NULL OR (phase = ANY (ARRAY['Prospecto'::text, 'Brief recibido'::text, 'Cotización enviada'::text, 'Negociación'::text, 'Ganado'::text, 'Perdido'::text])));

ALTER TABLE public.deals
  ADD CONSTRAINT deals_pkey PRIMARY KEY (id);

ALTER TABLE public.collection_processes
  ADD CONSTRAINT collection_processes_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE SET NULL;

ALTER TABLE public.cotizaciones
  ADD CONSTRAINT cotizaciones_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE SET NULL;

ALTER TABLE public.deal_documents
  ADD CONSTRAINT deal_documents_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE SET NULL;

ALTER TABLE public.deals
  ADD CONSTRAINT deals_status_propuesta_chk CHECK (status_propuesta IS NULL OR (status_propuesta = ANY (ARRAY['Por hacer'::text, 'Haciendo'::text, 'Listo'::text])));

GRANT ALL ON public.deals TO anon;

GRANT ALL ON public.deals TO authenticated;

GRANT ALL ON public.deals TO service_role;

CREATE TRIGGER deals_set_updated
  BEFORE UPDATE ON public.deals
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.document_blocks (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  block_id       bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  block_content  text,
  block_type     text,
  author_name    text,
  author_email   text,
  deal_id        uuid,
  sort_order     numeric,
  created_at     timestamp with time zone,
  updated_at     timestamp with time zone,
  checklist_data text,
  document_json  text
);

ALTER TABLE public.document_blocks
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.document_blocks
  ADD CONSTRAINT document_blocks_block_type_chk
    CHECK (block_type IS NULL OR (block_type = ANY (ARRAY['Texto'::text, 'Checklist'::text, 'Archivo'::text, 'Divisor'::text, 'Minuta'::text])));

ALTER TABLE public.document_blocks
  ADD CONSTRAINT document_blocks_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id) ON DELETE SET NULL;

ALTER TABLE public.document_blocks
  ADD CONSTRAINT document_blocks_pkey PRIMARY KEY (id);

GRANT ALL ON public.document_blocks TO anon;

GRANT ALL ON public.document_blocks TO authenticated;

GRANT ALL ON public.document_blocks TO service_role;

CREATE TRIGGER document_blocks_set_updated
  BEFORE UPDATE ON public.document_blocks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.documents (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  document_name text,
  project_code  text,
  category      text,
  file_url      text,
  uploaded_by   text,
  upload_date   date,
  version       text,
  notes         text,
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  updated_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.documents
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.documents
  ADD CONSTRAINT documents_category_chk
    CHECK
    (category IS NULL OR (category = ANY (ARRAY['Propuesta'::text, 'Contrato'::text, 'Entregable'::text, 'Guía de discusión'::text, 'Reporte'::text, 'Presentación'::text,
    'Otro'::text, 'Timeline'::text, 'Calendario'::text])));

ALTER TABLE public.documents
  ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

GRANT ALL ON public.documents TO anon;

GRANT ALL ON public.documents TO authenticated;

GRANT ALL ON public.documents TO service_role;

CREATE TRIGGER documents_set_updated
  BEFORE UPDATE ON public.documents
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.expense_audit_logs (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  "timestamp"    text,
  expense_id     uuid,
  action         text,
  user_email     text,
  user_name      text,
  comments       text,
  expense_number text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.expense_audit_logs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.expense_audit_logs
  ADD CONSTRAINT expense_audit_logs_action_chk
    CHECK (action IS NULL OR (action = ANY (ARRAY['Creado'::text, 'Editado'::text, 'Enviado a aprobación'::text, 'Aprobado'::text, 'Rechazado'::text, 'Eliminado'::text])));

ALTER TABLE public.expense_audit_logs
  ADD CONSTRAINT expense_audit_logs_pkey PRIMARY KEY (id);

GRANT ALL ON public.expense_audit_logs TO anon;

GRANT ALL ON public.expense_audit_logs TO authenticated;

GRANT ALL ON public.expense_audit_logs TO service_role;

CREATE TRIGGER expense_audit_logs_set_updated
  BEFORE UPDATE ON public.expense_audit_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.expense_comments (
  id           uuid                     DEFAULT gen_random_uuid() NOT NULL,
  comment      text,
  expense_id   uuid,
  author_email text,
  author_name  text,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at   timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.expense_comments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.expense_comments
  ADD CONSTRAINT expense_comments_pkey PRIMARY KEY (id);

GRANT ALL ON public.expense_comments TO anon;

GRANT ALL ON public.expense_comments TO authenticated;

GRANT ALL ON public.expense_comments TO service_role;

CREATE TRIGGER expense_comments_set_updated
  BEFORE UPDATE ON public.expense_comments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.expense_line_items (
  id          uuid                     DEFAULT gen_random_uuid() NOT NULL,
  description text,
  expense_id  uuid,
  category    text,
  amount      numeric(14,2),
  date        date,
  receipt     jsonb,
  notes       text,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  updated_at  timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.expense_line_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.expense_line_items
  ADD CONSTRAINT expense_line_items_category_chk
    CHECK
    (category IS NULL OR (category = ANY (ARRAY['Viáticos'::text, 'Transporte'::text, 'Alimentación'::text, 'Hospedaje'::text, 'Compras menores'::text, 'Papelería'::text,
    'Materiales'::text, 'Otros'::text])));

ALTER TABLE public.expense_line_items
  ADD CONSTRAINT expense_line_items_pkey PRIMARY KEY (id);

GRANT ALL ON public.expense_line_items TO anon;

GRANT ALL ON public.expense_line_items TO authenticated;

GRANT ALL ON public.expense_line_items TO service_role;

CREATE TRIGGER expense_line_items_set_updated
  BEFORE UPDATE ON public.expense_line_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.expenses (
  id                 uuid                     DEFAULT gen_random_uuid() NOT NULL,
  expense_number     bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description        text,
  amount             numeric(14,2),
  category           text,
  payment_method     text,
  cost_center        text,
  project_code       text,
  currency           text,
  expense_date       date,
  status             text,
  receipt            jsonb,
  notes              text,
  created_by         text,
  approved_by        text,
  rejection_reason   text,
  petty_cash_fund_id uuid,
  created_at         timestamp with time zone DEFAULT now() NOT NULL,
  updated_at         timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.expenses
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_category_chk
    CHECK
    (category IS NULL OR (category = ANY (ARRAY['Viáticos'::text, 'Transporte'::text, 'Alimentación'::text, 'Hospedaje'::text, 'Compras menores'::text, 'Papelería'::text,
    'Materiales'::text, 'Otros'::text])));

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_cost_center_chk
    CHECK (cost_center IS NULL OR (cost_center = ANY (ARRAY['Reclutamiento e Incentivos'::text, 'Logística'::text, 'Moderaciones'::text, 'Management'::text, 'Otros'::text])));

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text])));

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_payment_method_chk
    CHECK (payment_method IS NULL OR (payment_method = ANY (ARRAY['Caja chica'::text, 'Tarjeta corporativa'::text, 'Reembolso empleado'::text])));

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

ALTER TABLE public.expense_audit_logs
  ADD CONSTRAINT expense_audit_logs_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE SET NULL;

ALTER TABLE public.expense_comments
  ADD CONSTRAINT expense_comments_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE SET NULL;

ALTER TABLE public.expense_line_items
  ADD CONSTRAINT expense_line_items_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE SET NULL;

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Borrador'::text, 'Enviado a aprobación'::text, 'Aprobado'::text, 'Rechazado'::text])));

GRANT ALL ON public.expenses TO anon;

GRANT ALL ON public.expenses TO authenticated;

GRANT ALL ON public.expenses TO service_role;

CREATE INDEX expenses_status_idx ON public.expenses (status);

CREATE TRIGGER expenses_set_updated
  BEFORE UPDATE ON public.expenses
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.invoices (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  invoice_number text,
  project_code   text,
  client         text,
  type           text,
  amount         numeric(14,2),
  currency       text,
  issue_date     date,
  due_date       date,
  status         text,
  pdf_url        text,
  notes          text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.invoices
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text])));

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Pendiente'::text, 'Pagada'::text, 'Vencida'::text, 'Cancelada'::text])));

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_type_chk CHECK (type IS NULL OR (type = ANY (ARRAY['Factura'::text, 'Nota de crédito'::text])));

GRANT ALL ON public.invoices TO anon;

GRANT ALL ON public.invoices TO authenticated;

GRANT ALL ON public.invoices TO service_role;

CREATE TRIGGER invoices_set_updated
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.messages (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  message_id        bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  channel           text,
  sender_name       text,
  sender_email      text,
  content           text,
  sent_at           timestamp with time zone,
  parent_message_id text,
  reactions         text,
  pinned            boolean,
  attachments       text,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  updated_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.messages
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.messages
  ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

GRANT ALL ON public.messages TO anon;

GRANT ALL ON public.messages TO authenticated;

GRANT ALL ON public.messages TO service_role;

CREATE TRIGGER messages_set_updated
  BEFORE UPDATE ON public.messages
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.migration_logs (
  id               uuid                     DEFAULT gen_random_uuid() NOT NULL,
  project_code     text,
  board_id         text,
  migrated         numeric,
  failed           numeric,
  skipped          numeric,
  status           text,
  duration_seconds numeric,
  run_by_id        uuid,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.migration_logs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.migration_logs
  ADD CONSTRAINT migration_logs_pkey PRIMARY KEY (id);

ALTER TABLE public.migration_logs
  ADD CONSTRAINT migration_logs_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Completed'::text, 'Partial'::text, 'Error'::text])));

GRANT ALL ON public.migration_logs TO anon;

GRANT ALL ON public.migration_logs TO authenticated;

GRANT ALL ON public.migration_logs TO service_role;

CREATE TRIGGER migration_logs_set_updated
  BEFORE UPDATE ON public.migration_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.participants (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  full_name      text,
  email          text,
  phone          text,
  id_number      text,
  city           text,
  gender         text,
  age            numeric,
  total_sessions numeric,
  notes          text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.participants
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.participants
  ADD CONSTRAINT participants_gender_chk CHECK (gender IS NULL OR (gender = ANY (ARRAY['Femenino'::text, 'Masculino'::text, 'Otro'::text])));

ALTER TABLE public.participants
  ADD CONSTRAINT participants_pkey PRIMARY KEY (id);

GRANT ALL ON public.participants TO anon;

GRANT ALL ON public.participants TO authenticated;

GRANT ALL ON public.participants TO service_role;

CREATE TRIGGER participants_set_updated
  BEFORE UPDATE ON public.participants
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.payments (
  id                      uuid                     DEFAULT gen_random_uuid() NOT NULL,
  payment_id              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  po_id                   text,
  invoice_id              text,
  project_code            text,
  type                    text,
  amount                  numeric(14,2),
  payment_date            date,
  method                  text,
  reference               text,
  status                  text,
  notes                   text,
  supplier_name           text,
  currency                text,
  attachment              jsonb,
  due_date                date,
  supplier_invoice_number text,
  destination_account     text,
  source_company          text,
  source_bank             text,
  source_account          text,
  created_at              timestamp with time zone DEFAULT now() NOT NULL,
  updated_at              timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.payments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.payments
  ADD CONSTRAINT payments_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text])));

ALTER TABLE public.payments
  ADD CONSTRAINT payments_method_chk CHECK (method IS NULL OR (method = ANY (ARRAY['Transferencia'::text, 'Cheque'::text, 'Efectivo'::text, 'Otro'::text])));

ALTER TABLE public.payments
  ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE public.payments
  ADD CONSTRAINT payments_source_bank_chk
    CHECK
    (source_bank IS NULL OR (source_bank = ANY (ARRAY['BBVA'::text, 'Banorte'::text, 'Santander'::text, 'HSBC'::text, 'Banamex / Citibanamex'::text, 'Scotiabank'::text,
    'Banregio'::text, 'Inbursa'::text, 'Afirme'::text, 'Otro'::text])));

ALTER TABLE public.payments
  ADD CONSTRAINT payments_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Programado'::text, 'Realizado'::text, 'Cancelado'::text])));

ALTER TABLE public.payments
  ADD CONSTRAINT payments_type_chk CHECK (type IS NULL OR (type = ANY (ARRAY['Pago a proveedor'::text, 'Cobro de cliente'::text])));

GRANT ALL ON public.payments TO anon;

GRANT ALL ON public.payments TO authenticated;

GRANT ALL ON public.payments TO service_role;

CREATE INDEX payments_status_idx ON public.payments (status);

CREATE TRIGGER payments_set_updated
  BEFORE UPDATE ON public.payments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.petty_cash_funds (
  id                      uuid                     DEFAULT gen_random_uuid() NOT NULL,
  fund_name               text,
  initial_amount          numeric(14,2),
  current_balance         numeric(14,2),
  cost_center             text,
  status                  text,
  last_replenishment_date date,
  notes                   text,
  created_at              timestamp with time zone DEFAULT now() NOT NULL,
  updated_at              timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.petty_cash_funds
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.petty_cash_funds
  ADD CONSTRAINT petty_cash_funds_cost_center_chk
    CHECK (cost_center IS NULL OR (cost_center = ANY (ARRAY['Reclutamiento e Incentivos'::text, 'Logística'::text, 'Moderaciones'::text, 'Management'::text, 'Otros'::text])));

ALTER TABLE public.petty_cash_funds
  ADD CONSTRAINT petty_cash_funds_pkey PRIMARY KEY (id);

ALTER TABLE public.expenses
  ADD CONSTRAINT expenses_petty_cash_fund_id_fkey FOREIGN KEY (petty_cash_fund_id) REFERENCES public.petty_cash_funds(id) ON DELETE SET NULL;

ALTER TABLE public.petty_cash_funds
  ADD CONSTRAINT petty_cash_funds_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Activo'::text, 'Cerrado'::text])));

GRANT ALL ON public.petty_cash_funds TO anon;

GRANT ALL ON public.petty_cash_funds TO authenticated;

GRANT ALL ON public.petty_cash_funds TO service_role;

CREATE TRIGGER petty_cash_funds_set_updated
  BEFORE UPDATE ON public.petty_cash_funds
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.po_attachments (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  name              text,
  purchase_order_id uuid,
  file_url          text,
  description       text,
  uploaded_by_email text,
  uploaded_by_name  text,
  uploaded_at       timestamp with time zone,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  updated_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.po_attachments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.po_attachments
  ADD CONSTRAINT po_attachments_pkey PRIMARY KEY (id);

GRANT ALL ON public.po_attachments TO anon;

GRANT ALL ON public.po_attachments TO authenticated;

GRANT ALL ON public.po_attachments TO service_role;

CREATE TRIGGER po_attachments_set_updated
  BEFORE UPDATE ON public.po_attachments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.po_audit_logs (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  "timestamp"       timestamp with time zone,
  purchase_order_id uuid,
  action            text,
  user_email        text,
  user_name         text,
  comments          text,
  po_number         text,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  updated_at        timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.po_audit_logs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.po_audit_logs
  ADD CONSTRAINT po_audit_logs_action_chk
    CHECK
    (action IS NULL OR (action = ANY (ARRAY['Creada'::text, 'Editada'::text, 'Enviada'::text, 'Aprobada'::text, 'Rechazada'::text, 'Cancelada'::text, 'Eliminada'::text,
    'Enviada a aprobación'::text, 'Email enviado'::text])));

ALTER TABLE public.po_audit_logs
  ADD CONSTRAINT po_audit_logs_pkey PRIMARY KEY (id);

GRANT ALL ON public.po_audit_logs TO anon;

GRANT ALL ON public.po_audit_logs TO authenticated;

GRANT ALL ON public.po_audit_logs TO service_role;

CREATE TRIGGER po_audit_logs_set_updated
  BEFORE UPDATE ON public.po_audit_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.po_line_items (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  description    text,
  po_id          text,
  category       text,
  quantity       numeric,
  unit_price     numeric(14,2),
  total          numeric(14,2),
  parent_item_id text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.po_line_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.po_line_items
  ADD CONSTRAINT po_line_items_pkey PRIMARY KEY (id);

GRANT ALL ON public.po_line_items TO anon;

GRANT ALL ON public.po_line_items TO authenticated;

GRANT ALL ON public.po_line_items TO service_role;

CREATE TRIGGER po_line_items_set_updated
  BEFORE UPDATE ON public.po_line_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.projects (
  id                        uuid                     DEFAULT gen_random_uuid() NOT NULL,
  project_code              text,
  full_name                 text,
  status                    text,
  client                    text,
  budget                    numeric(14,2),
  start_date                date,
  end_date                  date,
  description               text,
  tematica                  text,
  timeline_status           text,
  timeline_url              text,
  timeline_updated_at       timestamp with time zone,
  teams_channel_url         text,
  teams_channel_status      text,
  deal_vinculado_id         uuid,
  lider_id                  uuid,
  muestra                   text,
  muestra_imagen            text,
  instrucciones_de_analisis text,
  last_analysis_json        text,
  last_analysis_at          timestamp with time zone,
  created_by                text,
  created_at                timestamp with time zone,
  updated_at                timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.projects
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.projects
  ADD CONSTRAINT projects_deal_vinculado_id_fkey FOREIGN KEY (deal_vinculado_id) REFERENCES public.deals(id) ON DELETE SET NULL;

ALTER TABLE public.projects
  ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE public.projects
  ADD CONSTRAINT projects_status_chk
    CHECK (status IS NULL OR (status = ANY (ARRAY['Prospecto'::text, 'En curso'::text, 'Finalizado'::text, 'Cancelado'::text, 'Activo'::text, 'Stand by'::text])));

ALTER TABLE public.projects
  ADD CONSTRAINT projects_teams_channel_status_chk
    CHECK (teams_channel_status IS NULL OR (teams_channel_status = ANY (ARRAY['Pendiente'::text, 'Creando'::text, 'Listo'::text, 'Error'::text])));

ALTER TABLE public.projects
  ADD CONSTRAINT projects_timeline_status_chk CHECK (timeline_status IS NULL OR (timeline_status = ANY (ARRAY['Pendiente'::text, 'Listo'::text, 'Error'::text])));

GRANT ALL ON public.projects TO anon;

GRANT ALL ON public.projects TO authenticated;

GRANT ALL ON public.projects TO service_role;

CREATE INDEX projects_project_code_idx ON public.projects (project_code);

CREATE TRIGGER projects_set_updated
  BEFORE UPDATE ON public.projects
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.projects_analistas (
  project_id uuid                     NOT NULL,
  user_id    uuid                     NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.projects_analistas
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.projects_analistas
  ADD CONSTRAINT projects_analistas_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE public.projects_analistas
  ADD CONSTRAINT projects_analistas_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

GRANT ALL ON public.projects_analistas TO anon;

GRANT ALL ON public.projects_analistas TO authenticated;

GRANT ALL ON public.projects_analistas TO service_role;

CREATE TABLE public.projects_asistentes (
  project_id uuid                     NOT NULL,
  user_id    uuid                     NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.projects_asistentes
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.projects_asistentes
  ADD CONSTRAINT projects_asistentes_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE public.projects_asistentes
  ADD CONSTRAINT projects_asistentes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

GRANT ALL ON public.projects_asistentes TO anon;

GRANT ALL ON public.projects_asistentes TO authenticated;

GRANT ALL ON public.projects_asistentes TO service_role;

CREATE TABLE public.projects_moderadores (
  project_id uuid                     NOT NULL,
  user_id    uuid                     NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.projects_moderadores
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.projects_moderadores
  ADD CONSTRAINT projects_moderadores_pkey PRIMARY KEY (project_id, user_id);

ALTER TABLE public.projects_moderadores
  ADD CONSTRAINT projects_moderadores_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;

GRANT ALL ON public.projects_moderadores TO anon;

GRANT ALL ON public.projects_moderadores TO authenticated;

GRANT ALL ON public.projects_moderadores TO service_role;

CREATE TABLE public.purchase_orders (
  id                  uuid                     DEFAULT gen_random_uuid() NOT NULL,
  po_number           text,
  project_code        text,
  supplier_name       text,
  issue_date          date,
  total_amount        numeric(14,2),
  status              text,
  pdf_url             text,
  notes               text,
  category            text,
  payment_terms       text,
  currency            text,
  created_by          text,
  approved_by         text,
  service_description text,
  billing_entity      text,
  email_sent_at       timestamp with time zone,
  email_sent_to       text,
  tipo_de_oc          text,
  rejection_reason    text,
  pdf_file            jsonb,
  pdf_base64          text,
  origen              text,
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  updated_at          timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.purchase_orders
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.purchase_orders
  ADD CONSTRAINT purchase_orders_category_chk
    CHECK (category IS NULL OR (category = ANY (ARRAY['Reclutamiento e Incentivos'::text, 'Logística'::text, 'Moderaciones'::text, 'Management'::text, 'Otros'::text])));

ALTER TABLE public.purchase_orders
  ADD CONSTRAINT purchase_orders_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text])));

ALTER TABLE public.purchase_orders
  ADD CONSTRAINT purchase_orders_origen_chk CHECK (origen IS NULL OR (origen = ANY (ARRAY['Migrada'::text, 'Sistema'::text])));

ALTER TABLE public.purchase_orders
  ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);

ALTER TABLE public.po_attachments
  ADD CONSTRAINT po_attachments_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;

ALTER TABLE public.po_audit_logs
  ADD CONSTRAINT po_audit_logs_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id) ON DELETE SET NULL;

ALTER TABLE public.purchase_orders
  ADD CONSTRAINT purchase_orders_status_chk
    CHECK
    (status IS NULL OR (status = ANY (ARRAY['Borrador'::text, 'Enviada a aprobación'::text, 'Aprobada'::text, 'Factura recibida'::text, 'Factura validada'::text,
    'Pago programado'::text, 'Pagada'::text, 'Cancelada'::text])));

ALTER TABLE public.purchase_orders
  ADD CONSTRAINT purchase_orders_tipo_de_oc_chk CHECK (tipo_de_oc IS NULL OR (tipo_de_oc = ANY (ARRAY['Normal'::text, 'Anticipo'::text, 'Cierre'::text])));

GRANT ALL ON public.purchase_orders TO anon;

GRANT ALL ON public.purchase_orders TO authenticated;

GRANT ALL ON public.purchase_orders TO service_role;

CREATE INDEX purchase_orders_status_idx ON public.purchase_orders (status);

CREATE INDEX purchase_orders_project_code_idx ON public.purchase_orders (project_code);

CREATE TRIGGER purchase_orders_set_updated
  BEFORE UPDATE ON public.purchase_orders
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.recruitment_rows (
  id               uuid                     DEFAULT gen_random_uuid() NOT NULL,
  row_name         text,
  project_code     text,
  board_name       text,
  participant_name text,
  email            text,
  phone            text,
  id_number        text,
  status           text,
  "group"          text,
  parent_row_id    text,
  level            numeric,
  nda_sent         boolean,
  nda_sent_date    timestamp with time zone,
  notes            text,
  source_form      text,
  deleted_at       text,
  cell_data        text,
  row_order        numeric,
  board_id         text,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.recruitment_rows
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.recruitment_rows
  ADD CONSTRAINT recruitment_rows_pkey PRIMARY KEY (id);

GRANT ALL ON public.recruitment_rows TO anon;

GRANT ALL ON public.recruitment_rows TO authenticated;

GRANT ALL ON public.recruitment_rows TO service_role;

CREATE INDEX recruitment_rows_phone_idx ON public.recruitment_rows (phone);

CREATE INDEX recruitment_rows_project_code_idx ON public.recruitment_rows (project_code);

CREATE INDEX recruitment_rows_participant_name_idx ON public.recruitment_rows USING gin (participant_name public.gin_trgm_ops);

CREATE INDEX recruitment_rows_email_idx ON public.recruitment_rows (email);

CREATE TRIGGER recruitment_rows_set_updated
  BEFORE UPDATE ON public.recruitment_rows
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.rubro_assignments (
  id               uuid                     DEFAULT gen_random_uuid() NOT NULL,
  rubro            text,
  assigned_user_id uuid,
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.rubro_assignments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.rubro_assignments
  ADD CONSTRAINT rubro_assignments_pkey PRIMARY KEY (id);

GRANT ALL ON public.rubro_assignments TO anon;

GRANT ALL ON public.rubro_assignments TO authenticated;

GRANT ALL ON public.rubro_assignments TO service_role;

CREATE TRIGGER rubro_assignments_set_updated
  BEFORE UPDATE ON public.rubro_assignments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.shared_views (
  id                   uuid                     DEFAULT gen_random_uuid() NOT NULL,
  view_name            text,
  board_id             text,
  project_code         text,
  board_name           text,
  token                text,
  filters_json         text,
  visible_columns_json text,
  created_by           text,
  active               boolean,
  type                 text,
  shared_token         text,
  view_order           numeric,
  created_at           timestamp with time zone DEFAULT now() NOT NULL,
  updated_at           timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.shared_views
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.shared_views
  ADD CONSTRAINT shared_views_pkey PRIMARY KEY (id);

ALTER TABLE public.shared_views
  ADD CONSTRAINT shared_views_type_chk CHECK (type IS NULL OR (type = ANY (ARRAY['Internal'::text, 'External'::text])));

GRANT ALL ON public.shared_views TO anon;

GRANT ALL ON public.shared_views TO authenticated;

GRANT ALL ON public.shared_views TO service_role;

CREATE UNIQUE INDEX shared_views_token_uniq ON public.shared_views (token)
  WHERE token IS NOT NULL AND token <> ''::text;

CREATE TRIGGER shared_views_set_updated
  BEFORE UPDATE ON public.shared_views
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.supplier_invoices (
  id               uuid                     DEFAULT gen_random_uuid() NOT NULL,
  invoice_number   text,
  po_id            text,
  supplier_id      text,
  supplier_name    text,
  po_number        text,
  amount           numeric(14,2),
  currency         text,
  pdf_file         jsonb,
  xml_file         jsonb,
  support_file     jsonb,
  status           text,
  upload_date      timestamp with time zone,
  uploaded_by      text,
  review_notes     text,
  reviewed_by      text,
  reviewed_at      timestamp with time zone,
  project_code     text,
  supplier_comment text,
  subtotal         numeric(14,2),
  iva_rate         numeric(6,4),
  iva_amount       numeric(14,2),
  retencion_iva    numeric(14,2),
  retencion_isr    numeric(14,2),
  created_at       timestamp with time zone DEFAULT now() NOT NULL,
  updated_at       timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.supplier_invoices
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.supplier_invoices
  ADD CONSTRAINT supplier_invoices_currency_chk CHECK (currency IS NULL OR (currency = ANY (ARRAY['MXN'::text, 'USD'::text])));

ALTER TABLE public.supplier_invoices
  ADD CONSTRAINT supplier_invoices_pkey PRIMARY KEY (id);

ALTER TABLE public.supplier_invoices
  ADD CONSTRAINT supplier_invoices_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Pendiente'::text, 'En revisión'::text, 'Validada'::text, 'Rechazada'::text])));

GRANT ALL ON public.supplier_invoices TO anon;

GRANT ALL ON public.supplier_invoices TO authenticated;

GRANT ALL ON public.supplier_invoices TO service_role;

CREATE INDEX supplier_invoices_status_idx ON public.supplier_invoices (status);

CREATE TRIGGER supplier_invoices_set_updated
  BEFORE UPDATE ON public.supplier_invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.suppliers (
  id              uuid                     DEFAULT gen_random_uuid() NOT NULL,
  supplier_name   text,
  tax_id          text,
  contact_name    text,
  email           text,
  phone           text,
  bank_name       text,
  bank_account    text,
  notes           text,
  categories      text[],
  identifier      text,
  address         text,
  tax_regime      text,
  person_type     text,
  country         text,
  access_token    text,
  portal_password text,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.suppliers
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.suppliers
  ADD CONSTRAINT suppliers_categories_chk
    CHECK
    (categories IS NULL OR categories <@ ARRAY['Reclutamiento e Incentivos'::text, 'Logística'::text, 'Moderaciones'::text, 'Management'::text, 'Otros'::text,
    'RECLUTAMIENTO'::text, 'MODERADORES'::text]);

ALTER TABLE public.suppliers
  ADD CONSTRAINT suppliers_person_type_chk CHECK (person_type IS NULL OR (person_type = ANY (ARRAY['Física'::text, 'Moral'::text])));

ALTER TABLE public.suppliers
  ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);

ALTER TABLE public.suppliers
  ADD CONSTRAINT suppliers_tax_regime_chk
    CHECK
    (tax_regime IS NULL OR (tax_regime = ANY (ARRAY['General de Ley Personas Morales'::text, 'RESICO'::text, 'Régimen de Incorporación Fiscal'::text,
    'Actividades Empresariales y Profesionales'::text,
    'Sueldos y Salarios'::text, 'Arrendamiento'::text, 'Sin obligaciones fiscales'::text, 'Otro'::text, 'Persona Física con Actividad Empresarial'::text])));

GRANT ALL ON public.suppliers TO anon;

GRANT ALL ON public.suppliers TO authenticated;

GRANT ALL ON public.suppliers TO service_role;

CREATE TRIGGER suppliers_set_updated
  BEFORE UPDATE ON public.suppliers
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.task_comments (
  id              uuid                     DEFAULT gen_random_uuid() NOT NULL,
  task_id         text,
  message_id      text,
  task_name       text,
  channel         text,
  sender_name     text,
  sender_email    text,
  content         text,
  sent_at         timestamp with time zone,
  is_thread_reply boolean,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  updated_at      timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.task_comments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.task_comments
  ADD CONSTRAINT task_comments_pkey PRIMARY KEY (id);

GRANT ALL ON public.task_comments TO anon;

GRANT ALL ON public.task_comments TO authenticated;

GRANT ALL ON public.task_comments TO service_role;

CREATE TRIGGER task_comments_set_updated
  BEFORE UPDATE ON public.task_comments
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.tasks (
  id             uuid                     DEFAULT gen_random_uuid() NOT NULL,
  task_name      text,
  project_code   text,
  status         text,
  assigned_to    text,
  start_date     date,
  end_date       date,
  parent_task_id text,
  "order"        numeric,
  notes          text,
  board_name     text,
  board_id       text,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  updated_at     timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.tasks
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tasks
  ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

ALTER TABLE public.tasks
  ADD CONSTRAINT tasks_status_chk CHECK (status IS NULL OR (status = ANY (ARRAY['Pendiente'::text, 'En progreso'::text, 'Completada'::text, 'Bloqueada'::text, 'Archivada'::text])));

GRANT ALL ON public.tasks TO anon;

GRANT ALL ON public.tasks TO authenticated;

GRANT ALL ON public.tasks TO service_role;

CREATE INDEX tasks_project_code_idx ON public.tasks (project_code);

CREATE TRIGGER tasks_set_updated
  BEFORE UPDATE ON public.tasks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.users (
  id                  uuid                     DEFAULT gen_random_uuid() NOT NULL,
  email               text,
  first_name          text,
  last_name           text,
  role                text,
  last_active_at      timestamp with time zone,
  purchase_level      text,
  cost_centers        text[],
  access_comercial    text,
  access_operacion    text,
  access_admin        text,
  access_finanzas     text,
  access_otros        text,
  max_approval_amount numeric(14,2),
  visible_pages       text[],
  hidden_from_chat    boolean,
  profile_photo       text,
  departamento        text,
  dashboard_widgets   text[],
  widget_layout       text,
  active_channel      text,
  cotizacion_rubros   text[],
  created_at          timestamp with time zone DEFAULT now() NOT NULL,
  updated_at          timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.users
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users
  ADD CONSTRAINT users_access_admin_chk CHECK (access_admin IS NULL OR (access_admin = ANY (ARRAY['Sin acceso'::text, 'Solo ver'::text, 'Editar'::text, 'Administrar'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_access_comercial_chk
    CHECK (access_comercial IS NULL OR (access_comercial = ANY (ARRAY['Sin acceso'::text, 'Solo ver'::text, 'Editar'::text, 'Administrar'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_access_finanzas_chk
    CHECK (access_finanzas IS NULL OR (access_finanzas = ANY (ARRAY['Sin acceso'::text, 'Solo ver'::text, 'Editar'::text, 'Administrar'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_access_operacion_chk
    CHECK (access_operacion IS NULL OR (access_operacion = ANY (ARRAY['Sin acceso'::text, 'Solo ver'::text, 'Editar'::text, 'Administrar'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_access_otros_chk CHECK (access_otros IS NULL OR (access_otros = ANY (ARRAY['Sin acceso'::text, 'Solo ver'::text, 'Editar'::text, 'Administrar'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_cost_centers_chk
    CHECK (cost_centers IS NULL OR cost_centers <@ ARRAY['Reclutamiento e Incentivos'::text, 'Logística'::text, 'Moderaciones'::text, 'Management'::text, 'Otros'::text]);

ALTER TABLE public.users
  ADD CONSTRAINT users_cotizacion_rubros_chk
    CHECK
    (cotizacion_rubros IS NULL OR cotizacion_rubros <@ ARRAY['Reclutamiento e incentivos'::text, 'Moderación'::text, 'Management'::text, 'Logística y operación'::text,
    'Back office'::text]);

ALTER TABLE public.users
  ADD CONSTRAINT users_dashboard_widgets_chk
    CHECK
    (dashboard_widgets IS NULL OR dashboard_widgets <@ ARRAY['Mis proyectos'::text, 'Mis tareas'::text, 'Próximos eventos'::text, 'Órdenes de compra'::text,
    'Menciones recientes'::text, 'Facturas recibidas'::text]);

ALTER TABLE public.users
  ADD CONSTRAINT users_departamento_chk CHECK (departamento IS NULL OR (departamento = ANY (ARRAY['Finanzas'::text, 'Análisis'::text, 'Reclutamiento'::text, 'Logística'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE public.collection_processes
  ADD CONSTRAINT collection_processes_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.commercial_dashboard_views
  ADD CONSTRAINT commercial_dashboard_views_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.deals
  ADD CONSTRAINT deals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.migration_logs
  ADD CONSTRAINT migration_logs_run_by_id_fkey FOREIGN KEY (run_by_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.projects
  ADD CONSTRAINT projects_lider_id_fkey FOREIGN KEY (lider_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.projects_analistas
  ADD CONSTRAINT projects_analistas_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.projects_asistentes
  ADD CONSTRAINT projects_asistentes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.projects_moderadores
  ADD CONSTRAINT projects_moderadores_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.rubro_assignments
  ADD CONSTRAINT rubro_assignments_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.users
  ADD CONSTRAINT users_purchase_level_chk
    CHECK (purchase_level IS NULL OR (purchase_level = ANY (ARRAY['Visor'::text, 'Creador'::text, 'Aprobador'::text, 'Finanzas'::text, 'Socios'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_role_chk CHECK (role IS NULL OR (role = ANY (ARRAY['Owner'::text, 'Socio'::text, 'Head'::text, 'Líder'::text, 'Coordinador'::text, 'Analista'::text])));

ALTER TABLE public.users
  ADD CONSTRAINT users_visible_pages_chk
    CHECK
    (visible_pages IS NULL OR visible_pages <@ ARRAY['Dashboard'::text, 'Chat'::text, 'CRM / Deals'::text, 'Dashboard comercial'::text, 'Cotizaciones'::text, 'Proyectos'::text,
    'Órdenes de compra'::text,
    'Proveedores'::text,
    'Pagos a proveedores'::text,
    'Facturas de proveedores'::text, 'Cobranza'::text, 'Costos por proyecto'::text, 'Dashboard financiero'::text, 'Tableros flexibles'::text, 'Comprobación de gastos'::text]);

GRANT ALL ON public.users TO anon;

GRANT ALL ON public.users TO authenticated;

GRANT ALL ON public.users TO service_role;

CREATE UNIQUE INDEX users_lower_idx ON public.users (lower(email));

CREATE TRIGGER users_set_updated
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();
